package com.example.timevault;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Select;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class MainUI extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Label labelTotalHours;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_8;
	@AutoGenerated
	private VerticalLayout verticalLayout_11;
	@AutoGenerated
	private Label labelDate;
	@AutoGenerated
	private VerticalLayout verticalLayout_7;
	@AutoGenerated
	private GridLayout gridLayout_1;
	@AutoGenerated
	private Button btnRetrieve;
	@AutoGenerated
	private ComboBox cbStaff;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private ComboBox cbMonth;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private ComboBox cbYear;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private ComboBox cbDepartment;
	@AutoGenerated
	private Label label_2;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		populate();
		populateStaff();
		// TODO add user code here
	}
	
	private void populate(){
		 
		for(String s: Const.CATEGORIES){
			cbDepartment.addItem(s);
		}
		
		for(String s: Const.MONTHS){			
			cbMonth.addItem(s);							
		}
		
		for(Integer s: Const.YEARS){
			cbYear.addItem(s);
		}
		
		cbDepartment.select(Const.CURRENT_CATEGORIES);
	
		cbMonth.select(Const.CURRENT_MONTHs);
		
		cbYear.select(Const.CURRENT_YEAR);
		
		
	}
	
	private void populateStaff(){
		TimeProcessUtil tpu = new TimeProcessUtil();
	 
		System.out.println("staff================");		
		String ip="192.168.21.94";
		tpu.load(ip, "Developer", "December", "2012");
		for(String s: tpu.getStaffLists(ip)){
			System.out.println(s);
			cbStaff.addItem(s);
		}
		
		for(String s : tpu.getStaffSummaryDatePunches()){
			System.out.println(s);
		}
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1);
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		mainLayout.addComponent(verticalLayout_5);
		mainLayout.setExpandRatio(verticalLayout_5, 1.0f);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
				
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		horizontalLayout_1.addComponent(verticalLayout_7);
		horizontalLayout_1.setExpandRatio(verticalLayout_7, 0.7f);
		
		// verticalLayout_8
		verticalLayout_8 = buildVerticalLayout_8();
		horizontalLayout_1.addComponent(verticalLayout_8);
		horizontalLayout_1.setExpandRatio(verticalLayout_8, 0.3f);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("100.0%");
		verticalLayout_7.setHeight("-1px");
		verticalLayout_7.setMargin(false);
		
		// gridLayout_1
		gridLayout_1 = buildGridLayout_1();
		verticalLayout_7.addComponent(gridLayout_1);
		
		return verticalLayout_7;
	}

	@AutoGenerated
	private GridLayout buildGridLayout_1() {
		// common part: create layout
		gridLayout_1 = new GridLayout();
		gridLayout_1.setStyleName("color=blue;");
		gridLayout_1.setImmediate(false);
		gridLayout_1.setWidth("100.0%");
		gridLayout_1.setHeight("100px");
		gridLayout_1.setMargin(false);
		gridLayout_1.setColumns(3);
		gridLayout_1.setRows(5);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Department");
		gridLayout_1.addComponent(label_2, 0, 0);
		gridLayout_1.setComponentAlignment(label_2, new Alignment(33));
		
		// cbDepartment
		cbDepartment = new ComboBox();
		cbDepartment.setImmediate(false);
		cbDepartment.setWidth("165px");
		cbDepartment.setHeight("-1px");
		gridLayout_1.addComponent(cbDepartment, 1, 0);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Year");
		gridLayout_1.addComponent(label_4, 0, 1);
		gridLayout_1.setComponentAlignment(label_4, new Alignment(33));
		
		// cbYear
		cbYear = new ComboBox();
		cbYear.setImmediate(false);
		cbYear.setWidth("165px");
		cbYear.setHeight("-1px");
		gridLayout_1.addComponent(cbYear, 1, 1);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("18px");
		label_5.setValue("Month");
		gridLayout_1.addComponent(label_5, 0, 2);
		gridLayout_1.setComponentAlignment(label_5, new Alignment(33));
		
		// cbMonth
		cbMonth = new ComboBox();
		cbMonth.setImmediate(false);
		cbMonth.setWidth("165px");
		cbMonth.setHeight("-1px");
		gridLayout_1.addComponent(cbMonth, 1, 2);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Staff");
		gridLayout_1.addComponent(label_3, 0, 3);
		gridLayout_1.setComponentAlignment(label_3, new Alignment(33));
		
		// cbStaff
		cbStaff = new ComboBox();
		cbStaff.setImmediate(false);
		cbStaff.setWidth("165px");
		cbStaff.setHeight("-1px");
		gridLayout_1.addComponent(cbStaff, 1, 3);
		
		// btnRetrieve
		btnRetrieve = new Button();
		btnRetrieve.setCaption("Retrieve");
		btnRetrieve.setImmediate(true);
		btnRetrieve.setWidth("-1px");
		btnRetrieve.setHeight("-1px");
		gridLayout_1.addComponent(btnRetrieve, 2, 3);
		
		return gridLayout_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_8() {
		// common part: create layout
		verticalLayout_8 = new VerticalLayout();
		verticalLayout_8.setImmediate(false);
		verticalLayout_8.setWidth("100.0%");
		verticalLayout_8.setHeight("-1px");
		verticalLayout_8.setMargin(false);
		
		// labelDate
		labelDate = new Label();
		labelDate.setImmediate(false);
		labelDate.setWidth("-1px");
		labelDate.setHeight("-1px");
		labelDate.setValue("Label");
		verticalLayout_8.addComponent(labelDate);
		
		// verticalLayout_11
		verticalLayout_11 = new VerticalLayout();
		verticalLayout_11.setImmediate(false);
		verticalLayout_11.setWidth("-1px");
		verticalLayout_11.setHeight("-1px");
		verticalLayout_11.setMargin(false);
		verticalLayout_8.addComponent(verticalLayout_11);
		
		return verticalLayout_8;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(false);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		verticalLayout_5.addComponent(table_1);
		verticalLayout_5.setExpandRatio(table_1, 1.0f);
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(false);
		
		// labelTotalHours
		labelTotalHours = new Label();
		labelTotalHours.setImmediate(false);
		labelTotalHours.setWidth("100.0%");
		labelTotalHours.setHeight("-1px");
		labelTotalHours.setValue("Total Hrs: ");
		verticalLayout_2.addComponent(labelTotalHours);
		verticalLayout_2.setComponentAlignment(labelTotalHours, new Alignment(
				34));
		
		return verticalLayout_2;
	}

}
